services:
  - docker
matrix:
  include:

    # Testing frontend.
    - language: node_js
      node_js:
        - "10.15.3"
      before_install:
        - cd backend/trafficnode-server
        - docker build -t verkehr-backend .
        - docker run -d -v ${PWD}:/usr/src/app -v /usr/src/app/node_modules -e PORT=8080 -p 8080:8080 --name verkehr-backend verkehr-backend
        - cd ../../frontend
        - docker build -t frontend .
#        - docker run -it --rm --name nodetestapp-running nodetestapp
      script:
        - npm test
      after_script:
        - docker stop verkehr-backend 

    # Testing backend.
    - language: node_js
      node_js:
        - "10.15.3"
      before_install:
        - cd backend/trafficnode-server
        - docker build -t nodetestapp .
#        - docker run -it --rm --name nodetestapp-running nodetestapp
      script:
        - npm test