services:
  - docker
matrix:
  include:

    # Testing frontend.
    - language: node_js
      node_js:
        - "10.15.3"
      before_install:
        - cd frontend
        - docker build -t nodetestapp .
#        - docker run -it --rm --name nodetestapp-running nodetestapp
      script:
        - npm test

    # Testing backend.
    - language: node_js
      node_js:
        - "10.15.3"
      before_install:
        - cd backend/trafficnode-server
        - docker build -t nodetestapp .
#        - docker run -it --rm --name nodetestapp-running nodetestapp
      script:
        - npm test