version: '3'
services:
  vk-frontend:
    build:
      context: ./frontend
    ports:
      - 80:80
  vk-backend:
    build:
      context: ./backend/trafficnode-server
    ports:
      - 8080:8080
    env_file:
      - verkehr.env
    links:
      - neo4j
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:3.5.5
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - 7474:7474
      - 7687:7687

