version: '3'
services:
  frontend:
    image: verkehr-frontend
    ports: 
      - 3000:3000
  backend:
    image: verkehr-backend
    ports:
      - 8080:8080
  neo4j:
    image: neo4j:3.5.5
    ports:
      - 7474:7474
      - 7687:7687

