version: '3'
services:
  frontend:
    image: verkehr-frontend
    ports: 
      - 3000:3000
  backend:
    image: verkehr-backend
    ports:
      - 8080:8080
    env_file:
      - verkehr.env
    links:
      - neo4j
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:3.5.5
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - 7474:7474
      - 7687:7687

