version: '3'
services:
  vk-computing:
    build:
      context: ./computing
    ports:
      - 55001:55001
    env_file:
      - vk-computing.env
  vk-frontend:
    build:
      context: ./frontend
    ports:
      - 80:80
    depends_on:
      - vk-backend
  vk-backend:
    build:
      context: ./backend/trafficnode-server
    ports:
      - 8080:8080
    env_file:
      - verkehr.env
    links:
      - neo4j
    depends_on:
      - neo4j
      - vk-computing
  neo4j:
    image: neo4j:3.5.5
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - 7474:7474
      - 7687:7687
  vk-importer:
    build:
      context: ./backend/map-data-parser
    links:
      - neo4j
    depends_on:
      - neo4j

