version: '3'
services:
  neo4j:
    image: neo4j:3.5.5
    volumes: 
      - "./resources/:/opt/resources"
    environment:
      - NEO4J_AUTH=neo4j/test
    ports:
      - 7474:7474
      - 7687:7687


