apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  ports:
  - name: "3000"
    port: 80
    targetPort: 3000
  selector:
    io.kompose.service: frontend
  type: LoadBalancer
status:
  loadBalancer: {}
