apiVersion: v1
data:
  GRPC_SERVER_ENDPOINT: "[::]:55001"
  NEO4J_URI: bolt://neo4j:7687
  NEO4J_USERNAME: neo4j
  NEO4J_PASSWORD: test
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: vk-computing-config
  name: vk-computing-config
