apiVersion: apps/v1
kind: Deployment
metadata:
  name: vk-frontend
spec: 
  selector:
    matchLabels: 
      run: vk-frontend
  replicas: 1
  template:
    metadata:
      labels:
        run: vk-frontend
    spec:
      containers:
      - name: vk-frontend
        image: 558558437971.dkr.ecr.eu-central-1.amazonaws.com/verkehr_frontend:latest
        ports:
        - containerPort: 80
